project:
  name: eventbridge-integration-solution-zendesk-attachment-processing
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-west-2
  s3_bucket: ''

tests:
  eventbridge:
    s3_bucket: ''
    template: ./packaged.yaml